//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicEntities1 : DbContext
    {
        public ClinicEntities1()
            : base("name=ClinicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDoctorAppointment> tblDoctorAppointment { get; set; }
        public virtual DbSet<tblLogin> tblLogin { get; set; }
        public virtual DbSet<tblLoginCurrent> tblLoginCurrent { get; set; }
        public virtual DbSet<tblMedicalDepartments> tblMedicalDepartments { get; set; }
        public virtual DbSet<tblMedicalStaff> tblMedicalStaff { get; set; }
        public virtual DbSet<tblPatients> tblPatients { get; set; }
        public virtual DbSet<tblPharmaceuticalManufacturing> tblPharmaceuticalManufacturing { get; set; }
        public virtual DbSet<tblPharmacy> tblPharmacy { get; set; }
        public virtual DbSet<tblTakeMedication> tblTakeMedication { get; set; }
        public virtual DbSet<vwDoctorAppointment> vwDoctorAppointment { get; set; }
        public virtual DbSet<vwLogin> vwLogin { get; set; }
        public virtual DbSet<vwLoginCurrent> vwLoginCurrent { get; set; }
        public virtual DbSet<vwMedicalDepartments> vwMedicalDepartments { get; set; }
        public virtual DbSet<vwMedicalStaff> vwMedicalStaff { get; set; }
        public virtual DbSet<vwPatients> vwPatients { get; set; }
        public virtual DbSet<vwPharmaceuticalManufacturing> vwPharmaceuticalManufacturing { get; set; }
        public virtual DbSet<vwPharmacy> vwPharmacy { get; set; }
        public virtual DbSet<vwTakeMedication> vwTakeMedication { get; set; }
    }
}
