//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicalStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMedicalStaff()
        {
            this.tblLogin = new HashSet<tblLogin>();
            this.tblLoginCurrent = new HashSet<tblLoginCurrent>();
            this.tblTakeMedication = new HashSet<tblTakeMedication>();
        }
    
        public int MedicalStaffID { get; set; }
        public string NameAndSurname { get; set; }
        public string MaleOrFemale { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string NameOfJob { get; set; }
        public string StatusOfEmployee { get; set; }
        public string BloodType { get; set; }
        public Nullable<int> MedicalDepartmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogin> tblLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoginCurrent> tblLoginCurrent { get; set; }
        public virtual tblMedicalDepartments tblMedicalDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTakeMedication> tblTakeMedication { get; set; }
    }
}
