//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPharmacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPharmacy()
        {
            this.tblTakeMedication = new HashSet<tblTakeMedication>();
        }
    
        public int PharmacyID { get; set; }
        public string NameOfTheDrug { get; set; }
        public string ScopeOfApplication { get; set; }
        public Nullable<int> QuantityOnCondition { get; set; }
        public string Note { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
    
        public virtual tblPharmaceuticalManufacturing tblPharmaceuticalManufacturing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTakeMedication> tblTakeMedication { get; set; }
    }
}
