//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLoginCurrent
    {
        public int LoginCurrentID { get; set; }
        public System.DateTime LoginDate { get; set; }
        public Nullable<int> MedicalStaffID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public int Expr1 { get; set; }
        public string NameAndSurname { get; set; }
        public int Expr2 { get; set; }
        public string Expr3 { get; set; }
    }
}
