//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMedicalDepartments
    {
        public int MedicalDepartmentID { get; set; }
        public string NameOfDepartment { get; set; }
        public Nullable<int> NumberOfFloor { get; set; }
        public string ContactPhoneOfDepartment { get; set; }
    }
}
