//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMedicalStaff
    {
        public int MedicalStaffID { get; set; }
        public string NameAndSurname { get; set; }
        public string MaleOrFemale { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string NameOfJob { get; set; }
        public string StatusOfEmployee { get; set; }
        public string BloodType { get; set; }
        public Nullable<int> MedicalDepartmentID { get; set; }
        public int Expr1 { get; set; }
        public string NameOfDepartment { get; set; }
    }
}
