//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPharmacy
    {
        public int PharmacyID { get; set; }
        public string NameOfTheDrug { get; set; }
        public string ScopeOfApplication { get; set; }
        public Nullable<int> QuantityOnCondition { get; set; }
        public string Note { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public int Expr1 { get; set; }
        public string ManufacturerName { get; set; }
    }
}
