//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPharmaceuticalManufacturing
    {
        public int ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
        public string AddressOfManufacturer { get; set; }
        public string PhoneNumberOfManufacturer { get; set; }
        public string EmailOfManufacturer { get; set; }
        public string Note { get; set; }
    }
}
